### PR TITLE
Tesseract planner improvements

### PR DESCRIPTION
**Pull request by mpowelson**
Adds some desired functions to the array and freespace planners. These correspond to the commits. They should be more or less independent of each other.

- Ability to pass coeffs through for each waypoing
- Ability to declare a waypoint a cost or constraint (note: Naming of this could change)
- Add a toleranced joint waypoint  (No cartesian mostly b/c its not in trajopt yet)
- Add desired configuration parameter - This is a joint cost applied to all of the points in the trajectory to pull it toward a desired configuration. Motivation was a desire to pull the trajectory away from singularities
- Fixed clang warnings

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong Be aware that in my effort to fix the Clang warnings I may have broken things in 5d8fc35. My example seemed to work fine, but I am getting `undefined reference to 'vtable for tesseract::tesseract_planning::TrajOptFreespacePlanner'` errors now when making these unit tests.

**Comment by mpowelson** [comment]
> @Levi-Armstrong Be aware that in my effort to fix the Clang warnings I may have broken things in [5d8fc35](https://github.com/ros-industrial-consortium/tesseract/commit/5d8fc35a8c6d4aae197bb3e5d2631a2e82205694). My example seemed to work fine, but I am getting `undefined reference to 'vtable for tesseract::tesseract_planning::TrajOptFreespacePlanner'` errors now when making these unit tests.

Nevermind. It was a Cmake Issue

**Comment by Levi-Armstrong** [comment]
Ok goof
