### PR TITLE
Add TesseractInitInfo

### PR DESCRIPTION
**Pull request by mpowelson**
This adds a struct that contains information that can be used to recreate a Tesseract at the time of it's initialization. It is a prerequisite to a forthcoming tesseract_ros2 PR that will add the initial state to the TesseractState. Essentially this is storing the initial state which the Environment comand history builds on.

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong It looks like the code coverage build failed?

**Comment by Levi-Armstrong** [comment]
Does it build locally?

**Comment by mpowelson** [comment]
> Does it build locally?

It builds. I have not tried to run code cov

**Comment by Levi-Armstrong** [comment]
It failed because the trajopt unit test segfaulted. 

```
2020-03-18T00:38:05.7435656Z [==========] Running 9 tests from 1 test case.
2020-03-18T00:38:05.7435738Z 
2020-03-18T00:38:05.7436013Z [----------] Global test environment set-up.
2020-03-18T00:38:05.7436079Z 
2020-03-18T00:38:05.7436350Z [----------] 9 tests from TesseractPlanningTrajoptUnit
2020-03-18T00:38:05.7436421Z 
2020-03-18T00:38:05.7436546Z [ RUN      ] TesseractPlanningTrajoptUnit.TrajoptFreespacePlanner0
2020-03-18T00:38:05.7436631Z 
2020-03-18T00:38:05.7436743Z Segmentation fault (core dumped)
```

**Comment by mpowelson** [comment]
So did the other builds succeed? What does the grey circle with exclamation mean? It says completed job.

**Comment by Levi-Armstrong** [comment]
It looks like it cancel all builds if one fails.

**Comment by mpowelson** [comment]
Can we turn that off? It is useful to know if melodic fails but kinetic succeeds. Or if the only thing wrong is clang formatting

**Comment by mpowelson** [comment]
@Levi-Armstrong I am doing a clean build and getting some include issues when building tests and codecov. For instance
`/tesseract_common_unit.cpp:1:10: fatal error: tesseract_common/macros.h: No such file or directory`

Can we trigger a build manually on the master branch somehow?

**Comment by mpowelson** [comment]
> @Levi-Armstrong I am doing a clean build and getting some include issues when building tests and codecov. For instance
> `/tesseract_common_unit.cpp:1:10: fatal error: tesseract_common/macros.h: No such file or directory`
> 
> Can we trigger a build manually on the master branch somehow?

Actually, the lcov one passed, so it must be something local

**Comment by Levi-Armstrong** [comment]
> Can we turn that off? It is useful to know if melodic fails but kinetic succeeds. Or if the only thing wrong is clang formatting

I disabled github actions fail-fast feature it in PR #255.
